metadata:
  labels:
    app: redis-cluster
  name: redis-dep
  namespace: default
spec:
  replicas: '2'
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
      name: Redis_Cluster
      namespace: default
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 493
          name: redis-cluster
        name: conf
      containers:
      - name: redis
        command:
        - "/conf/fix-ip.sh"
        - redis-server
        - "/conf/redis.conf"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 6379
          name: client
          protocol: TCP
        - containerPort: 16379
          name: gosip
          protocol: TCP
        volumeMounts:
        - mountPath: "/conf"
          name: conf
          readOnly: false
        image: redis:latest
        imagePullPolicy: Always
