metadata:
  labels:
    app: discourse
    tier: mail
  name: mail
  namespace: default
  annotations:
    member: sarat
    team: devops
spec:
  replicas: '1'
  selector:
    matchLabels:
      app: discourse
      tier: mail
  template:
    metadata:
      labels:
        app: discourse
        tier: mail
      namespace: default
      name: MailPod
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: mail
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 25
        command:
        - "/sbin/boot"
        image: kumarsarath588/mail-receiver:latest
        imagePullPolicy: Always
