# This workflow will install dsl tests
name: Setup & run calm-dsl tests

on:
  push:
    branches: [ topic/test_workflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup env
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Install requirements
      run: |
        make dev
    - name: Init DSL 
      run: |
        venv/bin/calm init dsl -i ${{ secrets.CALM_IP }} -P ${{ secrets.CALM_PORT }} -p ${{ secrets.CALM_PASSWORD }} -u ${{ secrets.CALM_USERNAME }} -pj ${{ secrets.CALM_PROJECT }}
    - name: Download test files
      run: |
        cd ~/.calm/.local
        wget http://10.46.1.165/calm-dsl-dev/tests.tar.gz.gpg
        gpg --yes --batch --passphrase=${{ secrets.DSL_PASSPHRASE }} tests.tar.gz.gpg
    - name: Run test
      run: |
        make test
    
        
