name: Setup & build calm-dsl
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup env
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
    - name: Install requirements
      run: |
        make dev
    - name: Build python package
      run: |
        make dist
    - name: Build docker image
      run: |
        make docker
