name: Setup & build calm-dsl on macos
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos 

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup env
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        export CFLAGS="-I$(brew --prefix openssl)/include"
        export LDFLAGS="-L$(brew --prefix openssl)/lib"     
    - name: Install requirements
      run: |
        make dev
    - name: Build python package
      run: |
        make dist
    - name: Build docker image
      run: |
        make docker
